# Generated by Django 5.0.3 on 2024-04-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='Address',
        ),
    ]
